server:
  port: 8083

spring:
  cloud:
    gcp:
      project-id: eventsphere-504909
      firestore:
        project-id: eventsphere-504909
      storage:
        project-id: eventsphere-504909

app:
  gcs:
    bucket-name: eventsphere-504909-media

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://eureka-server-1.eventsphere.internal:8761/eureka/,http://eureka-server-2.eventsphere.internal:8761/eureka/
